apiVersion: v1
kind: Service
metadata:
  labels:
    service: location_grpc_service
  name: location_grpc_service
spec:
  ports:
  - name: "5005"
    port: 6000
    targetPort: 6000
    nodePort: 30004
  selector:
    service: location_grpc_service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location_grpc_service
  name: location_grpc_service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location_grpc_service
  template:
    metadata:
      labels:
        service: location_grpc_service
    spec:
      containers:
      - image: joshbolten/location_grpc:latest
        name: location_grpc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_TOPIC
          value: test
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HOST
          value: my-cluster-kafka-bootstrap.my-kafka-project.svc.cluster.local
      restartPolicy: Always
