# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cperson.proto\"d\n\rpersonmessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x0f\n\x02id\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x05\n\x03_id\"4\n\x11PersonListMessage\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.personmessage\".\n\x14PersonRequestMessage\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x05\n\x03_id2\xa6\x01\n\rPersonService\x12(\n\x06\x43reate\x12\x0e.personmessage\x1a\x0e.personmessage\x12\x31\n\x08Retrieve\x12\x15.PersonRequestMessage\x1a\x0e.personmessage\x12\x38\n\x0bRetrieveAll\x12\x15.PersonRequestMessage\x1a\x12.PersonListMessageb\x06proto3'
)




_PERSONMESSAGE = _descriptor.Descriptor(
  name='personmessage',
  full_name='personmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='personmessage.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='personmessage.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='personmessage.company_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='personmessage.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='personmessage._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=116,
)


_PERSONLISTMESSAGE = _descriptor.Descriptor(
  name='PersonListMessage',
  full_name='PersonListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='persons', full_name='PersonListMessage.persons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=170,
)


_PERSONREQUESTMESSAGE = _descriptor.Descriptor(
  name='PersonRequestMessage',
  full_name='PersonRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonRequestMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='PersonRequestMessage._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=172,
  serialized_end=218,
)

_PERSONMESSAGE.oneofs_by_name['_id'].fields.append(
  _PERSONMESSAGE.fields_by_name['id'])
_PERSONMESSAGE.fields_by_name['id'].containing_oneof = _PERSONMESSAGE.oneofs_by_name['_id']
_PERSONLISTMESSAGE.fields_by_name['persons'].message_type = _PERSONMESSAGE
_PERSONREQUESTMESSAGE.oneofs_by_name['_id'].fields.append(
  _PERSONREQUESTMESSAGE.fields_by_name['id'])
_PERSONREQUESTMESSAGE.fields_by_name['id'].containing_oneof = _PERSONREQUESTMESSAGE.oneofs_by_name['_id']
DESCRIPTOR.message_types_by_name['personmessage'] = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['PersonListMessage'] = _PERSONLISTMESSAGE
DESCRIPTOR.message_types_by_name['PersonRequestMessage'] = _PERSONREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

personmessage = _reflection.GeneratedProtocolMessageType('personmessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:personmessage)
  })
_sym_db.RegisterMessage(personmessage)

PersonListMessage = _reflection.GeneratedProtocolMessageType('PersonListMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONLISTMESSAGE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonListMessage)
  })
_sym_db.RegisterMessage(PersonListMessage)

PersonRequestMessage = _reflection.GeneratedProtocolMessageType('PersonRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONREQUESTMESSAGE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonRequestMessage)
  })
_sym_db.RegisterMessage(PersonRequestMessage)



_PERSONSERVICE = _descriptor.ServiceDescriptor(
  name='PersonService',
  full_name='PersonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=221,
  serialized_end=387,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='PersonService.Create',
    index=0,
    containing_service=None,
    input_type=_PERSONMESSAGE,
    output_type=_PERSONMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='PersonService.Retrieve',
    index=1,
    containing_service=None,
    input_type=_PERSONREQUESTMESSAGE,
    output_type=_PERSONMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RetrieveAll',
    full_name='PersonService.RetrieveAll',
    index=2,
    containing_service=None,
    input_type=_PERSONREQUESTMESSAGE,
    output_type=_PERSONLISTMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONSERVICE)

DESCRIPTOR.services_by_name['PersonService'] = _PERSONSERVICE

# @@protoc_insertion_point(module_scope)
